### ISSUE TITLE
Create branches for different combos

### ISSUE THREAD

**Issue by ayyelle** [jliang22/ForeverALoans#1]
Already have: Home page menu + map search results

Need:

- Home page menu + list search results
- Slide-out/tab menu + map search results
- Slide-out tab menu + list search results

**Comment by tyler310** [comment]
Complete. Branches have been created for each of the four prorotypes.

**master**: home page + map search
**HomeMenu-List**: home page + list search
**PulloutMenu-Map**: pullout menu + map search
**PulloutMenu-List**: pullout menu + list
